---
title: "Final Project Proposal"
output: html_document
---

## Group Members  
- Hening Cui (hc3212);  
- Jialiang Hua (jh4323);  
- Congyang Xie (cx2257);  
- Wenhan Bao (wb2366);  
- Qihang Wu (qw2331)

## Project Title 
Who should be responsible for the innocent deaths?

## Motivation
In the wake of George Floyd’s murder, a number of protests arose across the nation. This motivates us to investigate innocent deaths under police violence and the association of confounders with the excessive police force. Although the majority of encounters that meet death with law enforcement officials present a lethal threat to officers or society, there are still some innocent people involved in the police action and the mortality should not be ignored. This project aims to analyze the data on people involved in police operations and results in death. Despite the assessment of the overuse of police force across geographical factors, this project also focuses on socioeconomic factors, political factors, and periodical patterns.

## Intended Final Products
- Summarize the main source data by race, age, gender, time, location, etc.  
- Explore potential association between number of innocent death and some factors including education level, crime rate, employment and unemployment rate, and some specific holidays, etc.

## Anticipated Data Sources
- [Innocent death by polices](https://www.kaggle.com/kannan1314/innocent-deaths-caused-by-police-all-time)  
- Potential association between innocent death and other factors:  
  - [Education level](https://www.census.gov/data/tables/2020/demo/educational-attainment/cps-detailed-tables.html)  
  - Crime rate  
  - Rate of gun ownership  
  - Possible periodical trend (specific festival, 911, etc.)  
  - Employment/Unemployment rate  
  - Economic index (inflation rate, CPI)  
  - Funding of local Police Department

## Planned analyses/visualizations/coding challenges
- Data cleaning & Exploratory data analysis (EDA)  
- Statistical analysis, such as correlation analysis, regression analysis  
- Data visualization including boxplot, barplot, scatterplot, etc

## Planned Timeline
|          Date          |                Descriptions               |
|:----------------------:|:-----------------------------------------:|
| 11/09/2021             | Complete the proposal                     |
| 11/10/2021- 11/19/2021 | Data collection, cleaning, and analysis   |
| 11/20/2021- 12/02/2021 | Data analysis and some insights           |
| 12/03/2021- 12/09/2021 | Modify code, website and final output     |
| 12/10/2021             | Submit!!                                  |