---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, echo = FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(leaflet)
library(shiny)
library(treemap)
library(highcharter)
library(viridisLite)
library(forecast)
library(readxl)
library(rsconnect)



thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )
```

```{r data_import}
plot = 
  read_csv("./data/maindata.csv") %>% 
  separate(date_of_death, c("year", "month", "day")) %>% 
  filter(year != 2021)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
Year_choices =
  plot %>% 
  distinct(year) %>% 
  pull()

selectInput(
  "Year",
  label = h3("Select Year"),
  choices =Year_choices,
  selected = "2020"
)

state_choices =
  plot %>% 
  distinct(state) %>% 
  pull()

selectInput(
  "State",
  label = h3("Select State"),
  choices = state_choices,
  selected = "NY"
)
```


Column {data-width=450}
-----------------------------------------------------------------------



### Innocent death in U.S.


```{r}
renderHighchart({
  data("usgeojson")
  
pop_stat <- 
  read_excel("data/nst-est2019-01.xlsx",
             range = "A9:M60") %>% 
  select("state" = "West", "population" = "78347268") %>% 
  mutate(
    state = str_match(state, "[a-zA-Z ]+")
  )

  plotly = 
    plot %>%
    filter(year == input[["Year"]]) %>% 
    group_by(state) %>% 
    summarize(count = n()) %>% 
    mutate(state = state.name[match(state, state.abb)]) %>% 
    drop_na() %>% 
    left_join(pop_stat, by = "state") %>% 
    mutate(death_rate_per10e6 = round(count/population*1000000, digits = 2))

  highchart() %>%
    hc_add_series_map(usgeojson, plotly, name = "Innocent Death number",
                      value = "death_rate_per10e6", joinBy = c("woename", "state"),
                      dataLabels = list(enabled = TRUE,
                                        format = '{point.properties.postalcode}'))
})

```



### Trend of innocent death by month

```{r}
renderHighchart({
plot %>% 
  filter(     
    year == input[["Year"]],
    state ==input[["State"]]) %>% 
  group_by(month, state) %>% 
  summarize(count = n()) %>% 
  hchart("line", hcaes(x = month, y = count, group = state)) %>% 
  hc_add_theme(thm)
})
```

Column {data-width=550}
-----------------------------------------------------------------------

### Innocent death interactive map

```{r}
renderLeaflet({
  plot %>% 
    filter(
      year == input[["Year"]],
      state ==input[["State"]]
    ) %>% 
    mutate(lan = as.numeric((str_sub(latitude, end = -2))),
           lon = as.numeric(str_sub(longitude, end = -2)),
           label = str_c("<b>City: ", city, 
                         "<br>Age: ", age, 
                         "<br>Race: ", race,
                         "<br>Gender: ", gender,
                         "<br>Cause of death: ", highest_force,
                         sep = "")) %>%
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron ) %>% 
  addCircleMarkers(~lon, ~lan, popup = ~ label, radius = 1)
  })   
```



