---
title: "Visualization"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r, warning = FALSE,message = FALSE}
library(tidyverse)
library(viridis)
library(modelr)
library(mgcv)
library(gifski)
library(plotly)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

knitr::opts_chunk$set(
  fig.width = 8,
  fig.height = 6,
  out.width = "90%",
  warning = FALSE
)


```


```{r, warning = FALSE, message = FALSE, echo = FALSE}
plot_df = 
  read_csv("./data/maindata.csv") %>% 
  separate(date_of_death, c("year", "month", "day")) %>% 
  filter(year != 2021) %>% 
  mutate(year = as.double(year))
```


```{r, warning = FALSE,message = FALSE}
accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frm = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}
  
```

## Trend of death cases

### Overall death cases

```{r}
plot_year =
  plot_df %>%
  group_by(year) %>%
  summarize(count = n()) %>%
  accumulate_by(~ year) %>% 
  plot_ly(
    x = ~ year,
    y = ~ count,
    type = 'scatter',
    frame = ~ frm, 
    mode = 'lines',
    line = list(simplyfy = F, color = '#B5495B')
  ) %>%
  layout(
    xaxis = list(title = "Year",
                 zeroline = F),
    yaxis = list(title = "Number of innocent death",
                 zeroline = F)
  ) %>%
  
  animation_slider(hide = T)

plot_year
```

### Grouped by age


```{r, warning = FALSE, message = FALSE, echo = FALSE}

plot_age = 
  plot_df %>% 
  group_by(year,age_bin) %>% 
  summarize(count = n()) %>% 
  mutate(age_bin = as.factor(age_bin)) %>% 
  ungroup(year) %>% 
  accumulate_by(~ year) %>% 
  plot_ly(
    x = ~ year,
    y = ~ count,
    frame = ~ frm,
    type = 'scatter',
    mode = 'lines',
    line = list(simplyfy = F),
    color = ~ age_bin, 
    colors = c("#F596AA", "#E9A368", "#B481BB", "#838A2D", "#58B2DC")
  ) %>%
  layout(
    xaxis = list(title = "Year",
                 zeroline = F),
    yaxis = list(title = "Number of innocent death",
                 zeroline = F)
  )  %>%
  animation_opts(frame = 100,
                 transition = 0,
                 redraw = FALSE) %>% animation_slider(hide = T) 

plot_age 
```



### Grouped by gender

```{r, warning = FALSE, message = FALSE, echo = FALSE}
plot_gender =
  plot_df %>% 
  group_by(year, gender) %>% 
  summarize(count = n()) %>% 
  ungroup(year) %>% 
  accumulate_by(~ year) %>% 
  plot_ly(
    x = ~ year,
    y = ~ count,
    type = 'scatter',
    frame = ~ frm,
    mode = 'lines',
    line = list(simplyfy = F),
    color = ~ gender,
    colors = c("#F596AA", "#58B2DC")
  ) %>%
  layout(
    xaxis = list(title = "Year",
                 zeroline = F),
    yaxis = list(title = "Number of innocent death",
                 zeroline = F)
  ) %>%
  animation_opts(frame = 100,
                 transition = 0,
                 redraw = FALSE) %>% 
  animation_slider(hide = T)

plot_gender
```

### Grouped by race

```{r, warning = FALSE, message = FALSE, echo = FALSE}
plot_race =
  plot_df %>% 
  group_by(year, race) %>% 
  summarize(count = n()) %>% 
  ungroup(year) %>% 
  accumulate_by(~ year) %>% 
plot_ly(
    x = ~ year,
    y = ~ count,
    frame = ~ frm, 
    type = 'scatter',
    mode = 'lines',
    line = list(simplyfy = F),
    color = ~ race,
    colors = c("#F596AA", "#E9A368", "#B481BB", "#838A2D", "#58B2DC")
  ) %>%
  layout(
    xaxis = list(title = "Year",
                 zeroline = F),
    yaxis = list(title = "Number of innocent death",
                 zeroline = F)
  ) %>%
  animation_opts(frame = 100,
                 transition = 0,
                 redraw = FALSE) %>% 
  animation_slider(hide = T)

plot_race
```



